import {useEffect,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,Users,History} from 'lucide-react';
import {api,amount,compact} from '../../lib/api';

export const TokenActivity=({project:p,simulation})=>{
 const[tab,setTab]=useState('trades'),[trades,setTrades]=useState([]),[holders,setHolders]=useState([]),[error,setError]=useState(false),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);Promise.all([api.get(`/market/${p.id}/trades`),api.get(`/market/${p.id}/holders`)]).then(([t,h])=>{if(active){setTrades(t.data.items);setHolders(h.data.items);setError(false);}}).catch(()=>active&&setError(true)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[p.id,retry]);
 const mine=(simulation?.trades||[]).filter(t=>t.project_id===p.id).map(t=>({...t,trader:'You (practice)',mine:true}));
 const rows=tab==='mine'?mine:[...mine,...trades].slice(0,24);
 return <section className="token-activity" data-testid="token-activity"><div className="activity-tabs">{[['trades','Transactions'],['holders',`Holders (${amount(p.holders)})`],['mine','My trades'],['about','About']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'selected':''} data-testid={`activity-tab-${id}`}>{label}{id==='mine'&&mine.length>0&&<small>{mine.length}</small>}</button>)}</div>
  {loading?<div className="activity-empty" data-testid="activity-loading">Loading activity...</div>:error?<div className="activity-empty" data-testid="activity-error">Activity unavailable. <button className="text-link" onClick={()=>setRetry(v=>v+1)} data-testid="activity-retry">Try again</button></div>:tab==='about'?<div className="token-about" data-testid="token-about"><h3>What's in ${p.ticker}?</h3><p>{p.description}</p><dl><div><dt>Protocol</dt><dd>Pump.fun / PF</dd></div><div><dt>Trading pair</dt><dd>{p.ticker}/SOL</dd></div><div><dt>Token supply</dt><dd>{compact(p.supply)} {p.ticker}</dd></div><div><dt>Mint address</dt><dd>Not issued · preview token</dd></div><div><dt>Fill Asset</dt><dd>{p.asset} · not the trading pair</dd></div></dl></div>:tab==='holders'?<div className="activity-table-wrap"><table className="activity-table" data-testid="holders-table"><thead><tr><th>Rank</th><th>Holder</th><th>Supply held</th><th>Amount</th><th>Value</th></tr></thead><tbody>{holders.map(h=><tr key={h.rank} data-testid={`holder-row-${h.rank}`}><td>#{h.rank}</td><td><Users size={12}/> {h.label}</td><td>{h.percentage}%</td><td>{compact(h.quantity)}</td><td>${compact(h.value_usd)}</td></tr>)}</tbody></table><p className="activity-note">Illustrative holder distribution. These are not real wallet addresses.</p></div>:rows.length?<div className="activity-table-wrap"><table className="activity-table" data-testid="transactions-table"><thead><tr><th>Time</th><th>Type</th><th>Amount ({p.ticker})</th><th>Total (SOL)</th><th>Trader</th></tr></thead><tbody>{rows.map(t=><tr key={t.id} className={t.mine?'your-trade':''} data-testid={`transaction-${t.id}`}><td title={new Date(t.executed_at).toLocaleString()}>{new Date(t.executed_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</td><td><span className={`trade-type ${t.side}`}>{t.side==='buy'?<ArrowDownLeft size={12}/>:<ArrowUpRight size={12}/>} {t.side.toUpperCase()}</span></td><td>{compact(t.quantity)}</td><td>{amount(t.sol_amount)}</td><td>{t.trader}</td></tr>)}</tbody></table><p className="activity-note">{tab==='mine'?'Your saved practice fills. No real funds or on-chain transactions.':'Sample activity and your simulated fills. Not live on-chain transactions.'}</p></div>:<div className="activity-empty" data-testid="no-personal-trades"><History size={25}/><strong>Your story starts with a trade.</strong><p>Try a simulated buy. Your fills will appear here.</p></div>}
 </section>;
};