import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Search,SlidersHorizontal,LayoutGrid,List,TrendingUp} from 'lucide-react';
import {api,amount,compact} from '../lib/api';
import {BagArt,TokenAvatar,Reveal} from './BagArt';

export const BagCard=({project:p})=><Link to={`/token/${p.id}`} className="bag-card market-bag-card" data-testid={`bag-card-${p.id}`}>
 <div className="bag-card-top"><div className="token-identity"><TokenAvatar project={p}/><span><strong>${p.ticker}</strong><small>{p.name}</small></span></div><span className={`market-change ${p.change_24h>=0?'positive':'negative'}`} data-testid={`card-change-${p.id}`}>{p.change_24h>=0?'+':''}{p.change_24h}% <ArrowUpRight size={12}/></span></div>
 <div className="card-market-metrics" data-testid={`card-metrics-${p.id}`}><div><span>Market cap</span><strong data-testid={`card-mcap-${p.id}`}>${compact(p.market_cap)}</strong></div><div><span>Volume 24h</span><strong data-testid={`card-volume-${p.id}`}>${compact(p.volume)}</strong></div><div><span>Holders</span><strong data-testid={`card-holders-${p.id}`}>{amount(p.holders)}</strong></div></div>
 <div className="card-bag-summary"><BagArt progress={p.progress}/><div><div className="card-bag-title"><span>{p.asset} BAG</span><strong>{p.progress}%</strong></div><div className="progress-track"><span style={{width:`${p.progress}%`,background:p.color}}/></div><small>{amount(p.asset_amount)} / {amount(p.asset_target)} {p.asset}</small></div></div>
 <div className="bag-card-footer"><span className="mode-badge">{p.mode}</span><span className={`inline-carry ${p.carry_status==='Active'?'positive':''}`}><i/>{p.carry_status==='Active'?'Carry active':'Carry idle'}</span><span>View & trade <ArrowUpRight size={13}/></span></div>
</Link>;

const MarketRow=({p})=><Link to={`/token/${p.id}`} className="market-list-row" data-testid={`token-row-${p.id}`}><div className="token-identity"><TokenAvatar project={p} small/><span><strong>${p.ticker}</strong><small>{p.name}</small></span></div><strong>${compact(p.market_cap)}</strong><span className={p.change_24h>=0?'positive':'negative'}>{p.change_24h>0?'+':''}{p.change_24h}%</span><span>${compact(p.volume)}</span><span>{amount(p.holders)}</span><span className="row-bag-progress"><small>{p.asset} · {p.progress}%</small><i><b style={{width:`${p.progress}%`}}/></i></span><ArrowUpRight size={15}/></Link>;

export const BagIndex=({featured=false})=>{
 const[projects,setProjects]=useState([]),[sort,setSort]=useState('trending'),[search,setSearch]=useState(''),[view,setView]=useState('grid'),[loading,setLoading]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(()=>api.get('/projects',{params:{sort,search}}).then(r=>{if(active){setProjects(r.data);setError(false);}}).catch(()=>active&&setError(true)).finally(()=>active&&setLoading(false)),180);return()=>{active=false;clearTimeout(timer);};},[sort,search,retry]);
 return <section className={`section page-width ${featured?'featured-market':'full-market'}`} id="bags" data-testid="bag-index-section">
  <Reveal className="section-heading"><div><span className="eyebrow">{featured?'PACKED WITH ACTIVITY':'THE BAG INDEX'}</span><h2 data-testid="bag-index-heading">{featured?'A few Bags to keep an eye on.':'Find your next Bag.'}</h2><p data-testid="bag-index-copy">{featured?'Discover the tokens. Follow the activity. Carry something good.':'Explore tokens, follow the market, and see what’s filling.'}</p></div>{featured?<Link to="/bags" className="text-link" data-testid="view-all-tokens">All tokens <ArrowUpRight size={17}/></Link>:<Link to="/launch" className="button primary" data-testid="index-launch">Launch a token <ArrowUpRight size={16}/></Link>}</Reveal>
  {!featured&&<div className="index-toolbar"><div className="sort-tabs" data-testid="bag-sort-tabs">{[['trending','Trending'],['newest','Newest'],['mcap','Market Cap'],['volume','Volume'],['closest','Closest to Full']].map(([id,label])=><button key={id} className={sort===id?'selected':''} data-testid={`sort-${id}`} onClick={()=>setSort(id)}>{id==='trending'&&<TrendingUp size={12}/>} {label}</button>)}<label className="more-sort"><SlidersHorizontal size={14}/><select aria-label="More sorting options" value={['opened','carry','holders'].includes(sort)?sort:''} onChange={e=>setSort(e.target.value)} data-testid="sort-more"><option value="" disabled>More</option><option value="opened">Most Bags Opened</option><option value="carry">Carry Active</option><option value="holders">Most Holders</option></select></label></div><div className="index-controls"><label className="search-field"><Search size={15}/><input aria-label="Search tokens" placeholder="Search name, ticker, asset..." value={search} onChange={e=>setSearch(e.target.value)} data-testid="bag-search"/></label><div className="view-toggle"><button aria-label="Grid view" aria-pressed={view==='grid'} onClick={()=>setView('grid')} data-testid="tokens-grid-view"><LayoutGrid size={15}/></button><button aria-label="List view" aria-pressed={view==='list'} onClick={()=>setView('list')} data-testid="tokens-list-view"><List size={15}/></button></div></div></div>}
  <div className="preview-label" data-testid="bag-index-data-note"><i/> Sample market data · practice trading available · no real funds</div>
  {error?<div className="empty-state" data-testid="bags-error">Couldn't load the tokens. <button className="text-link" onClick={()=>setRetry(r=>r+1)} data-testid="bags-retry">Try again</button></div>:loading?<div className="bag-grid" aria-busy="true" data-testid="bags-loading">{[0,1,2].map(i=><div className="bag-skeleton" key={i}/>)}</div>:projects.length?(view==='list'&&!featured?<div className="market-list"><div className="market-list-heading"><span>Token</span><span>Market cap</span><span>24h</span><span>Volume 24h</span><span>Holders</span><span>Bag progress</span><span/></div>{projects.map(p=><MarketRow key={p.id} p={p}/>)}</div>:<div className="bag-grid">{(featured?projects.slice(0,3):projects).map(p=><BagCard key={p.id} project={p}/>)}</div>):<div className="empty-state" data-testid="bags-empty"><BagArt progress={0}/><h3>No tokens by that name.</h3><p>Try another name, ticker, or reward asset.</p><button className="text-link" onClick={()=>setSearch('')} data-testid="bags-clear-search">Clear search <ArrowRight size={15}/></button></div>}
  {!featured&&!loading&&<p className="index-count" data-testid="token-results-count">{projects.length} tokens · Every one carries a Bag.</p>}
 </section>;
};