import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,Search,ChevronDown,SlidersHorizontal} from 'lucide-react';
import {api,amount,compact} from '../lib/api';
import {BagArt,TokenAvatar,Reveal} from './BagArt';

export const BagCard=({project:p,onOpen})=><button className="bag-card" data-testid={`bag-card-${p.id}`} onClick={()=>onOpen(p.id)}><div className="bag-card-top"><div className="token-identity"><TokenAvatar project={p}/><span><strong>${p.ticker}</strong><small>{p.name}</small></span></div><ArrowUpRight size={18}/></div><div className="bag-card-art"><span className="asset-label">{p.asset} BAG</span><BagArt progress={p.progress}/><span className={`carry-badge ${p.carry_status==='Active'?'active':''}`}><i/>Carry {p.carry_status}</span></div><div className="bag-value"><strong>{amount(p.asset_amount)} <small>{p.asset}</small></strong><span>{Math.round(p.progress)}<small>%</small></span></div><div className="progress-track"><span style={{width:`${p.progress}%`,background:p.color}}/></div><div className="bag-target"><span>of {amount(p.asset_target)} {p.asset}</span><span>Cycle #{String(p.cycle).padStart(2,'0')}</span></div><div className="bag-card-footer"><span className="mode-badge">{p.mode}</span><span>{compact(p.volume)} volume <ArrowUpRight size={12}/></span></div></button>;

export const BagIndex=({onOpen})=>{
 const[projects,setProjects]=useState([]),[sort,setSort]=useState('trending'),[search,setSearch]=useState(''),[all,setAll]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(()=>api.get('/projects',{params:{sort,search}}).then(r=>{if(active){setProjects(r.data);setError(false);}}).catch(()=>active&&setError(true)).finally(()=>active&&setLoading(false)),180);return()=>{active=false;clearTimeout(timer);};},[sort,search,retry]);
 return <section className="section page-width" id="bags" data-testid="bag-index-section"><Reveal className="section-heading"><div><span className="eyebrow">THE BAG INDEX</span><h2 data-testid="bag-index-heading">Good things. Getting full.</h2><p data-testid="bag-index-copy">A little activity goes a long way. Find a Bag to carry.</p></div><span className="hand-note tilted-note">there's a Bag for everyone ↙</span></Reveal><div className="index-toolbar"><div className="sort-tabs" data-testid="bag-sort-tabs">{[['trending','Trending'],['volume','Highest Volume'],['closest','Closest to Full']].map(([id,label])=><button key={id} className={sort===id?'selected':''} data-testid={`sort-${id}`} onClick={()=>setSort(id)}>{id==='trending'&&<FlameIcon/>}{label}</button>)}<label className="more-sort"><SlidersHorizontal size={14}/><select aria-label="More sorting options" value={['opened','carry'].includes(sort)?sort:''} onChange={e=>setSort(e.target.value)} data-testid="sort-more"><option value="" disabled>More</option><option value="opened">Most Bags Opened</option><option value="carry">Carry Active</option></select></label></div><label className="search-field"><Search size={15}/><input aria-label="Search bags" placeholder="Find your Bag..." value={search} onChange={e=>setSearch(e.target.value)} data-testid="bag-search"/></label></div><div className="preview-label" data-testid="bag-index-data-note"><i/> Preview collection · illustrative activity, not live market data</div>{error?<div className="empty-state" data-testid="bags-error">Couldn't unpack the Bags. <button className="text-link" onClick={()=>setRetry(r=>r+1)} data-testid="bags-retry">Try again</button></div>:loading?<div className="bag-grid" aria-busy="true" data-testid="bags-loading">{[0,1,2].map(i=><div className="bag-skeleton" key={i}/>)}</div>:projects.length?<div className="bag-grid">{projects.slice(0,all?100:3).map(p=><BagCard key={p.id} project={p} onOpen={onOpen}/>)}</div>:<div className="empty-state" data-testid="bags-empty"><BagArt progress={0}/><h3>No Bags by that name.</h3><p>Try another token or reward asset.</p><button className="text-link" onClick={()=>setSearch('')} data-testid="bags-clear-search">Clear search <ArrowRight size={15}/></button></div>}{!loading&&projects.length>3&&<div className="center-action"><button className="button subtle" onClick={()=>setAll(!all)} data-testid="bags-show-all">{all?'Show fewer Bags':`Explore all ${projects.length} Bags`} <ChevronDown size={15} style={{transform:all?'rotate(180deg)':''}}/></button></div>}</section>;
};
const FlameIcon=()=> <span aria-hidden="true">↗</span>;