import {useEffect,useState} from 'react';
import {ArrowUpRight,Trophy} from 'lucide-react';
import {api,amount,compact} from '../lib/api';
import {Reveal,TokenAvatar} from './BagArt';
const tabs=[['opened','Most Bags Opened'],['biggest','Biggest Bags'],['fastest','Fastest Bags'],['profits','Carry Profits'],['active','Most Active']];
export const Leaderboard=({onOpen})=>{
 const[category,setCategory]=useState('opened'),[rows,setRows]=useState([]),[error,setError]=useState(false),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);api.get('/leaderboard',{params:{category}}).then(r=>{if(active){setRows(r.data);setError(false);}}).catch(()=>active&&setError(true)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[category,retry]);
 const metric=p=>({opened:`${p.cycle-1} Bags opened`,biggest:`${amount(p.target_sol)} SOL`,fastest:`${p.fastest_hours} hours`,profits:`${p.carry_pnl>=0?'+':''}${p.carry_pnl} SOL`,active:`$${compact(p.volume)}`})[category];
 return <section id="leaderboard" className="section page-width leaderboard-section" data-testid="leaderboard-section"><Reveal className="section-heading"><div><span className="eyebrow">A LITTLE FRIENDLY COMPETITION</span><h2 data-testid="leaderboard-heading">Big Bag energy.</h2></div><Trophy className="leaderboard-trophy" size={40} strokeWidth={1.3}/></Reveal><div className="leaderboard-tabs">{tabs.map(([id,label])=><button key={id} className={category===id?'active':''} onClick={()=>setCategory(id)} data-testid={`leaderboard-tab-${id}`}>{label}</button>)}</div><div className="leaderboard-table" data-testid="leaderboard-results">{error?<div className="empty-state" data-testid="leaderboard-error">Couldn't load the leaderboard.<button className="text-link" onClick={()=>setRetry(v=>v+1)} data-testid="leaderboard-retry">Try again</button></div>:loading?<div className="leaderboard-loading" data-testid="leaderboard-loading">Unpacking the ranks...</div>:rows.map((p,i)=><button key={p.id} className="leaderboard-row" onClick={()=>onOpen(p.id)} data-testid={`leaderboard-rank-${i+1}`}><span className={`rank rank-${i+1}`}>0{i+1}</span><TokenAvatar project={p} small/><span className="leaderboard-name"><strong>${p.ticker}</strong><small>{p.name}</small></span><span className="leaderboard-asset">{p.asset} BAG</span><strong className="rank-metric">{metric(p)}</strong><ArrowUpRight size={16}/></button>)}</div><p className="preview-label" data-testid="leaderboard-data-note">Illustrative rankings. The real stories are still being packed.</p></section>;
};